apiVersion: v1
kind: Service
metadata:
    name: firstkubernetes-service
    namespace: hellokubernetes
spec:
    selector:
        app: firstkubernetes
    ports:
        - name: application
          protocol: TCP
          port: 8080
          targetPort: 8080
    type: ClusterIP